### ISSUE TITLE
About CHARACTERISTIC_UUID

### ISSUE THREAD

**Issue by net0040** [teach310/ToioFaceM5#1]
Thank you for your work, when Atoms3 is installed on the Toio Mate, and the Toio Cube is powered on, when I Press Button, Face keep showing that toio is no connection, face No change.

Excuse me,The following parameters in code :

#define SERVICE_UUID "0B21C05A-44C2-47CC-BFEF-4F7165C33908"
#define CHARACTERISTIC_UUID "B3C450C9-5FC5-48F6-9EFD-D588E494F462"

Is this parameter an example, or where can I get it from?
I understand, this is an atoms3 parameter, used to build a server, thanks.

**Comment by net0040** [comment]
atoms3 face is wink ,and toio cube‘s blue power light flashes.

**Comment by teach310** [comment]
Hi, net0040

> Is this parameter an example, or where can I get it from?

I got it from the following page.

https://www.uuidgenerator.net/

This product acts as a ble peripheral.
And toio cube is also a ble peripheral.

So you have to prepare a Central to use this product.
The example flow is as follows.

```
central -> m5atoms3: connect
central -> toio: connect
central -> m5atoms3: set expression
```

I'm developing a sample central with Unity.
https://github.com/teach310/ATOMMateForToioSample/blob/main/Assets/Scripts/ToioFace.cs

**Comment by teach310** [comment]
I'm closing the issue, so feel free to reopen it if you have any further concerns or questions!
